disabled_rules:
- trailing_whitespace
- xctfail_message
- identifier_name
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 150
    error: 4000
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 40
    error: 70
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 200
    error: 300
file_length:
    warning: 500
    error: 1000
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
force_cast: warning # implicitly
reporter: "xcode"
