# Uncomment the next line to define a global platform for your project
# platform :ios, ’15.0’

target 'MarvelApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelApp
    pod 'Alamofire', '~> 5.5'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SDWebImage'

  target 'MarvelAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelAppUITests' do
    # Pods for testing
  end

end
